export { generateRandomIP } from './randomIPGenerator'
export { domainRegex } from './domain.regex'
export { ipv4Regex } from './ip.regex'
export { replaceLastSectionOfIp } from './changeHostIpAddress'
export { toCamelCase } from './stringToCamelCase'
export { getRandomPort } from './randomPort'
export { openVpnTemplate } from './openVpnTemplate'